# Generated by Django 5.2.7 on 2025-10-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='color',
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='weight',
        ),
    ]
