# Generated by Django 5.2.7 on 2025-10-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0002_delete_brand_remove_yarn_color_remove_yarn_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countrie', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='yarn',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yarn',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yarns', to='yarns.brand'),
        ),
    ]
