# Generated by Django 5.2.7 on 2025-10-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0003_brand_yarn_popularity_yarn_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='yarn',
            name='popularity',
        ),
        migrations.AddField(
            model_name='yarn',
            name='weight',
            field=models.FloatField(default=50.0, help_text='weight'),
        ),
        migrations.AddField(
            model_name='yarn',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarns', to='yarns.material'),
        ),
    ]
