# Generated by Django 5.2.7 on 2025-10-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0004_material_remove_yarn_popularity_yarn_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='brand',
        ),
        migrations.AddField(
            model_name='yarn',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yarns', to='yarns.brand'),
        ),
    ]
