# Generated by Django 5.2.7 on 2025-10-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yarns', '0005_remove_yarn_brand_yarn_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='countrie',
            new_name='country',
        ),
    ]
